# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.
use Mix.Config
Code.require_file("config/secret.exs")

# General application configuration
config :discuss,
  ecto_repos: [Discuss.Repo]

# Configures the endpoint
config :discuss, Discuss.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "X5VbJk5y9wJoGjPJmm0n7wpCnMkHbUBQW2LDCEis4rC3MWWPi7MFsjoaGdc33zll",
  render_errors: [view: Discuss.ErrorView, accepts: ~w(html json)],
  pubsub: [name: Discuss.PubSub,
           adapter: Phoenix.PubSub.PG2]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"

# configuration ueberauth-github module
config :ueberauth, Ueberauth,
providers: [
  github: { Ueberauth.Strategy.Github }
]

# client_id and client_secret is generated by GitHub
#  a) Login to github
#  b) Settings -> Developer Settings -> OAuth Apps -> Register New App
#  c) type in the details about your app (url, name etc.)
config :ueberauth, Ueberauth.Strategy.Github.OAuth,
  client_id: Secret.get_client_id(),
  client_seceret: Secret.get_client_secret()
